on:
  push:
    branches: ["main"]

name: Build and deploy on push

env:
  RUST_CHANNEL: stable
  WEIDING_PRIVATE_DEPLOY_KEY: "${{ secrets.WEIDING_PRIVATE_DEPLOY_KEY }}"
jobs:
  build:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        node-version: '16'

    - name: Install asteroids deps
      uses: actions/setup-node@v2

    - name: Build website
      run: ./scripts/build.sh
      env:
        GITHUB_TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
